export const ALL_POST_REQUEST = "ALL_POST_REQUEST"
export const ALL_POST_SUCCESS = "ALL_POST_SUCCESS"
export const ALL_POST_FAIL = "ALL_POST_FAIL"


export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST"
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS"
export const CREATE_POST_FAIL = "CREATE_POST_FAIL"
export const CREATE_POST_RESET = "CREATE_POST_RESET"

export const CLEAR_ERRORS = "CLEAR_ERRORS"